Feature/russian format dates
SunR1sen/react-file-viewer pull request #1
Opened 2021-02-10 23:15 UTC by SunR1sen

2021-02-11 11:58 UTC, BANOnotIT requested changes
в реквесте слишком много левых файлов, связанных с прогоном `eslint --fix`. такое лучше делать отдельным mr'ом.

2021-02-11 11:58 UTC, BANOnotIT commented on src/components/drivers/xlsx-viewer.jsx
> +        if (cellData.t === "d" && cellData.w.match(/\d{2}\//g)) {
1. неправильная регулярка. у тебя формат дат вполне себе известен. а если будет формат "11 11/20" то она у тебя сработает
2. вместо match заюзай [test](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test)
3. не забывай о `^` и `$`, без них регулярка имеет слишком много проблем

в остальном подход именно такой который я ожидал увидеть и о котором сам просил.

2021-02-11 11:58 UTC, BANOnotIT commented on src/utils/helper.js
> +};
погоди, то есть формат фактически может работать через replaceAll?.. 
Если так то конечно лучше попробовать его и не закидывать лишнюю библиотеку. Хотя с другой стороны мы конечно же потеряем некоторую обработку неправильных дат.

2021-02-15 22:38 UTC, BANOnotIT approved these changes

2021-02-15 22:38 UTC, BANOnotIT commented on src/components/drivers/xlsx-viewer.jsx
> +        if (cellData.t === "d" && /^\d{2}\/\d{2}\/\d{2}$/g.test(cellData.w)) {
обычно такие regexp'ы выносят в отдельную константу

2021-02-16 21:09 UTC, SunR1sen commented on src/components/drivers/xlsx-viewer.jsx
> +        if (cellData.t === "d" && /^\d{2}\/\d{2}\/\d{2}$/g.test(cellData.w)) {
Убрать G чтобы не забыть

2021-03-18 19:13 UTC, merged